version: '3.8'

services:
  # Сервис для PostgreSQL
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: dombyra
      POSTGRES_PASSWORD: dombyrapassword
      POSTGRES_DB: dombyra
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dombyra']
      interval: 10s
      timeout: 5s
      retries: 5

  # Сервис для Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgres://dombyra:dombyrapassword@postgres:5432/dombyra
      JWT_SECRET: your_jwt_secret_key
    ports:
      - '5000:5000'

  # Сервис для Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://backend:5000
    ports:
      - '3000:3000'

volumes:
  postgres_data:
